Pipelines. Testing

diff --git a/TFproviderTest.yml b/TFproviderTest.yml
--- a/TFproviderTest.yml
+++ b/TFproviderTest.yml
@@ -55,6 +55,9 @@ pipelines:
             - GKE_CLUSTER=tf-provider-xray-$(date +%s)
             - fozzie checkout native-steps
             - fozzie gke/create_cluster
+            #- gcloud auth activate-service-account --key-file="${SERVICE_ACCOUNT_JSON}"
+            #- gcloud container clusters get-credentials "${GKE_CLUSTER}" --zone "${GKE_ZONE}" --project "${GKE_PROJECT}"
+            # testing
             - echo "Creating Artifactory Secret"
             - echo $FOZZIE_HOME
             - kubectl create secret generic artifactory-license --from-file=$FOZZIE_HOME/native-steps/license/artifactory.cluster.license
@@ -115,146 +118,146 @@ pipelines:
             - echo "Artifactory password ${NEW_RT_PASSWORD}"
           onFailure:
             - echo "JFrog Artifactory and Xray creation failed."
-            - send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. Pipeline failed on <${step_url}|${step_name}> step"
-            - fozzie checkout native-steps
-            - echo "Removing GKE cluster"
-            - fozzie gke/authorize
-            - fozzie gke/delete_cluster
-            - echo "Removing DNS entry"
-            - export URL="${GKE_CLUSTER}-rt.jfrog.tech"
-            - fozzie dns/delete
+#            - send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. Pipeline failed on <${step_url}|${step_name}> step"
+#            - fozzie checkout native-steps
+#            - echo "Removing GKE cluster"
+#            - fozzie gke/authorize
+#            - fozzie gke/delete_cluster
+#            - echo "Removing DNS entry"
+#            - export URL="${GKE_CLUSTER}-rt.jfrog.tech"
+#            - fozzie dns/delete
           onComplete:
             - echo "JFrog Artifactory and Xray Job Complete"
 
-      - name: build_and_run_tf_provider
-        type: Bash
-        configuration:
-          priority: 1
-          timeoutSeconds: 1800 # 30 minutes
-          runtime:
-            type: image
-            image:
-              auto:
-                language: go
-                versions:
-                  - "1.18"
-          integrations:
-            - name: partnersSlack
-            - name: gkeEnvVars
-            - name: Partnership_GitHub
-          inputSteps:
-            - name: fozzie_gke_jfrog_rt_xray_create
-          inputResources:
-            - name: GitHubTFProviderXrayRepoJFrog1
-          environmentVariables:
-            NEW_RT_PASSWORD: ${int_gkeEnvVars_new_rt_password}
-        execution:
-          onStart:
-            - echo "Preparing for work..."
-            - echo "Make sure that changes merged into development branch don't break the TF provider"
-            - go version
-            - echo "Install Terraform"
-            - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DA418C88A3219F7B
-            - sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
-            - sudo apt install terraform && terraform -version
-            - echo "Install GoReleaser"
-            - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
-            - sudo apt update
-            - sudo apt install goreleaser
-          onExecute:
-            - add_run_variables gitHubRepoUrl=${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositorySshUrl}
-            - add_run_variables TFProviderRepo=$(echo ${gitHubRepoUrl} | sed -e 's/git@/@/g' -e 's/:/\//g')
-            - add_run_variables repoFolder=$(echo "${res_GitHubTFProviderXrayRepoJFrog1_gitRepoFullName}" | sed -e 's/.*\///g')
-            - cd ${res_GitHubTFProviderXrayRepoJFrog1_resourcePath}
-            - echo "Verify the code contents merged feature branch with development branch"
-            - git branch && ls -al
-            - echo "Add variables needed to run Terraform Provider Xray"
-            - export JFROG_URL=${jdp_url} && echo ${JFROG_URL}
-            - export ARTIFACTORY_USERNAME=admin
-            - export ARTIFACTORY_PASSWORD=${NEW_RT_PASSWORD} && echo ${ARTIFACTORY_PASSWORD}
-            - echo "Get cookie to generate Access token. There is no public API to generate Access token using username and password"
-            - >-
-              export COOKIES=$(curl -c - "${JFROG_URL}/ui/api/v1/ui/auth/login?_spring_security_remember_me=false" \
-                            --header "accept: application/json, text/plain, */*" \
-                            --header "content-type: application/json;charset=UTF-8" \
-                            --header "x-requested-with: XMLHttpRequest" \
-                            -d '{"user":"'"${ARTIFACTORY_USERNAME}"'","password":"'"${ARTIFACTORY_PASSWORD}"'","type":"login"}' | grep FALSE)
-            - export REFRESHTOKEN=$(echo $COOKIES | grep REFRESHTOKEN | awk '{print $7 }')
-            - export ACCESSTOKEN=$(echo $COOKIES | grep ACCESSTOKEN | awk '{print $14 }') # awk returns null on Mac, and the actual key on Ubuntu
-            - >-
-              export ACCESS_KEY=$(curl -g --request GET "${JFROG_URL}/ui/api/v1/system/security/token?services[]=all" \
-                                  --header "accept: application/json, text/plain, */*" \
-                                  --header "x-requested-with: XMLHttpRequest" \
-                                  --header "cookie: ACCESSTOKEN=${ACCESSTOKEN}; REFRESHTOKEN=${REFRESHTOKEN}")
-            - export XRAY_ACCESS_TOKEN=${ACCESS_KEY}
-            - echo "Unset ARTIFACTORY_USERNAME and ARTIFACTORY_PASSWORD, acceptance test will use XRAY_ACCESS_TOKEN instead"
-            - unset ARTIFACTORY_USERNAME && unset ARTIFACTORY_PASSWORD
-            - export TF_ACC=1
-            - make acceptance
-            - make install -e TARGET_ARCH=linux_amd64
-          onSuccess:
-            - send_notification partnersSlack --text "Terraform Provider Xray run is completed. Version ${NEXT_PROVIDER_VERSION}."
-          onFailure:
-            - echo "Failure"
-            - send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. Pipeline failed on <${step_url}|${step_name}> step"
-          onComplete:
-            - echo "Complete"
-
-      - name: pr_info_add_rt_version
-        type: Bash
-        configuration:
-          integrations:
-            - name: partnersSlack
-            - name: partnership_jfrog_io
-            - name: Partnership_GitHub
-          inputSteps:
-            - name: build_and_run_tf_provider
-          inputResources:
-            - name: GitHubTFProviderXrayRepoJFrog1
-        execution:
-          onStart:
-            - echo "Preparing for work..."
-            - echo "Collect information about the PR and send a Slack notification"
-          onExecute:
-            - printenv
-            - export PR_URL=${res_GitHubTFProviderXrayRepoJFrog1_commitUrl}
-            - export PR_COMMITTER=${res_GitHubTFProviderXrayRepoJFrog1_committerLogin}
-            - export PR_BRANCH=${res_GitHubTFProviderXrayRepoJFrog1_headCommitRef}
-            ## PR_TITLE var is used in the Slack message. We need to escape &, > and < per Slack documentation.
-            ## They will be replaced with &amp;, &gt; and &lt; respectively.
-            - export PR_TITLE=$(echo ${res_GitHubTFProviderXrayRepoJFrog1_commitMessage:0:100}... | sed -e 's/\&/\&amp;/g' -e 's/>/\&gt;/g' -e 's/</\&lt;/g')
-            - >-
-              if [[ "${PR_URL}" == null ]]; then
-                echo "PR was not created (already exists from this head branch?). PR link is empty!"
-                exit 1
-              fi
-            - cd ${res_GitHubTFProviderXrayRepoJFrog1_resourcePath}
-            - git checkout -b ${res_GitHubTFProviderXrayRepoJFrog1_headCommitRef}
-            - sed -i -E "0,/(##\s.+\..+\..+\s\(.+\)).*/ s/(##\s.+\..+\..+\s\(.+\)).*/\1. Tested on Artifactory ${ARTIFACTORY_VERSION} and Xray ${XRAY_VERSION}/" CHANGELOG.md
-            - head -10 CHANGELOG.md
-            - git add CHANGELOG.md
-            - export REGEX="Changes to be committed*"
-            - export GIT_STATUS=$(git status)
-            - >-
-              if [[ ${GIT_STATUS} =~ ${REGEX} ]]; then
-                echo "Adding Artifactory and Xray versions to CHANGELOG.md"
-                git commit --author="JFrog CI <jfrog-solutions-ci+1@jfrog.com>" -m "JFrog Pipelines - Add Artifactory and Xray versions to CHANGELOG.md"
-                git push https://${res_GitHubTFProviderXrayRepoJFrog1_gitProvider_token}${TFProviderRepo}
-              else
-                echo "There is nothing to commit, Artifactory version didn't change since last commit"
-              fi
-          onSuccess:
-            - echo "Success"
-            - echo ${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}
-            - echo ${PR_URL}
-            - echo ${PR_TITLE}
-            - send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. A new PR was submitted by *${PR_COMMITTER}* - <${PR_URL}|${PR_TITLE}> branch *${PR_BRANCH}*. Changes tested successfully. <@U01H1SLSPA8> or <@UNDRUL1EU> please, review and merge."
-          onFailure:
-            - >-
-              if [[ "${PR_URL}" == null ]]; then
-                send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. Pipeline failed on <${step_url}|${step_name}> step. PR was not created (already exists from this head branch?)"
-              else
-                send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. Pipeline failed on <${step_url}|${step_name}> step"
-              fi
-          onComplete:
-            - echo "Cleaning up"
+#      - name: build_and_run_tf_provider
+#        type: Bash
+#        configuration:
+#          priority: 1
+#          timeoutSeconds: 1800 # 30 minutes
+#          runtime:
+#            type: image
+#            image:
+#              auto:
+#                language: go
+#                versions:
+#                  - "1.18"
+#          integrations:
+#            - name: partnersSlack
+#            - name: gkeEnvVars
+#            - name: Partnership_GitHub
+#          inputSteps:
+#            - name: fozzie_gke_jfrog_rt_xray_create
+#          inputResources:
+#            - name: GitHubTFProviderXrayRepoJFrog1
+#          environmentVariables:
+#            NEW_RT_PASSWORD: ${int_gkeEnvVars_new_rt_password}
+#        execution:
+#          onStart:
+#            - echo "Preparing for work..."
+#            - echo "Make sure that changes merged into development branch don't break the TF provider"
+#            - go version
+#            - echo "Install Terraform"
+#            - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DA418C88A3219F7B
+#            - sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+#            - sudo apt install terraform && terraform -version
+#            - echo "Install GoReleaser"
+#            - echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
+#            - sudo apt update
+#            - sudo apt install goreleaser
+#          onExecute:
+#            - add_run_variables gitHubRepoUrl=${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositorySshUrl}
+#            - add_run_variables TFProviderRepo=$(echo ${gitHubRepoUrl} | sed -e 's/git@/@/g' -e 's/:/\//g')
+#            - add_run_variables repoFolder=$(echo "${res_GitHubTFProviderXrayRepoJFrog1_gitRepoFullName}" | sed -e 's/.*\///g')
+#            - cd ${res_GitHubTFProviderXrayRepoJFrog1_resourcePath}
+#            - echo "Verify the code contents merged feature branch with development branch"
+#            - git branch && ls -al
+#            - echo "Add variables needed to run Terraform Provider Xray"
+#            - export JFROG_URL=${jdp_url} && echo ${JFROG_URL}
+#            - export ARTIFACTORY_USERNAME=admin
+#            - export ARTIFACTORY_PASSWORD=${NEW_RT_PASSWORD} && echo ${ARTIFACTORY_PASSWORD}
+#            - echo "Get cookie to generate Access token. There is no public API to generate Access token using username and password"
+#            - >-
+#              export COOKIES=$(curl -c - "${JFROG_URL}/ui/api/v1/ui/auth/login?_spring_security_remember_me=false" \
+#                            --header "accept: application/json, text/plain, */*" \
+#                            --header "content-type: application/json;charset=UTF-8" \
+#                            --header "x-requested-with: XMLHttpRequest" \
+#                            -d '{"user":"'"${ARTIFACTORY_USERNAME}"'","password":"'"${ARTIFACTORY_PASSWORD}"'","type":"login"}' | grep FALSE)
+#            - export REFRESHTOKEN=$(echo $COOKIES | grep REFRESHTOKEN | awk '{print $7 }')
+#            - export ACCESSTOKEN=$(echo $COOKIES | grep ACCESSTOKEN | awk '{print $14 }') # awk returns null on Mac, and the actual key on Ubuntu
+#            - >-
+#              export ACCESS_KEY=$(curl -g --request GET "${JFROG_URL}/ui/api/v1/system/security/token?services[]=all" \
+#                                  --header "accept: application/json, text/plain, */*" \
+#                                  --header "x-requested-with: XMLHttpRequest" \
+#                                  --header "cookie: ACCESSTOKEN=${ACCESSTOKEN}; REFRESHTOKEN=${REFRESHTOKEN}")
+#            - export XRAY_ACCESS_TOKEN=${ACCESS_KEY}
+#            - echo "Unset ARTIFACTORY_USERNAME and ARTIFACTORY_PASSWORD, acceptance test will use XRAY_ACCESS_TOKEN instead"
+#            - unset ARTIFACTORY_USERNAME && unset ARTIFACTORY_PASSWORD
+#            - export TF_ACC=1
+#            - make acceptance
+#            - make install -e TARGET_ARCH=linux_amd64
+#          onSuccess:
+#            - send_notification partnersSlack --text "Terraform Provider Xray run is completed. Version ${NEXT_PROVIDER_VERSION}."
+#          onFailure:
+#            - echo "Failure"
+#            - send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. Pipeline failed on <${step_url}|${step_name}> step"
+#          onComplete:
+#            - echo "Complete"
+#
+#      - name: pr_info_add_rt_version
+#        type: Bash
+#        configuration:
+#          integrations:
+#            - name: partnersSlack
+#            - name: partnership_jfrog_io
+#            - name: Partnership_GitHub
+#          inputSteps:
+#            - name: build_and_run_tf_provider
+#          inputResources:
+#            - name: GitHubTFProviderXrayRepoJFrog1
+#        execution:
+#          onStart:
+#            - echo "Preparing for work..."
+#            - echo "Collect information about the PR and send a Slack notification"
+#          onExecute:
+#            - printenv
+#            - export PR_URL=${res_GitHubTFProviderXrayRepoJFrog1_commitUrl}
+#            - export PR_COMMITTER=${res_GitHubTFProviderXrayRepoJFrog1_committerLogin}
+#            - export PR_BRANCH=${res_GitHubTFProviderXrayRepoJFrog1_headCommitRef}
+#            ## PR_TITLE var is used in the Slack message. We need to escape &, > and < per Slack documentation.
+#            ## They will be replaced with &amp;, &gt; and &lt; respectively.
+#            - export PR_TITLE=$(echo ${res_GitHubTFProviderXrayRepoJFrog1_commitMessage:0:100}... | sed -e 's/\&/\&amp;/g' -e 's/>/\&gt;/g' -e 's/</\&lt;/g')
+#            - >-
+#              if [[ "${PR_URL}" == null ]]; then
+#                echo "PR was not created (already exists from this head branch?). PR link is empty!"
+#                exit 1
+#              fi
+#            - cd ${res_GitHubTFProviderXrayRepoJFrog1_resourcePath}
+#            - git checkout -b ${res_GitHubTFProviderXrayRepoJFrog1_headCommitRef}
+#            - sed -i -E "0,/(##\s.+\..+\..+\s\(.+\)).*/ s/(##\s.+\..+\..+\s\(.+\)).*/\1. Tested on Artifactory ${ARTIFACTORY_VERSION} and Xray ${XRAY_VERSION}/" CHANGELOG.md
+#            - head -10 CHANGELOG.md
+#            - git add CHANGELOG.md
+#            - export REGEX="Changes to be committed*"
+#            - export GIT_STATUS=$(git status)
+#            - >-
+#              if [[ ${GIT_STATUS} =~ ${REGEX} ]]; then
+#                echo "Adding Artifactory and Xray versions to CHANGELOG.md"
+#                git commit --author="JFrog CI <jfrog-solutions-ci+1@jfrog.com>" -m "JFrog Pipelines - Add Artifactory and Xray versions to CHANGELOG.md"
+#                git push https://${res_GitHubTFProviderXrayRepoJFrog1_gitProvider_token}${TFProviderRepo}
+#              else
+#                echo "There is nothing to commit, Artifactory version didn't change since last commit"
+#              fi
+#          onSuccess:
+#            - echo "Success"
+#            - echo ${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}
+#            - echo ${PR_URL}
+#            - echo ${PR_TITLE}
+#            - send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. A new PR was submitted by *${PR_COMMITTER}* - <${PR_URL}|${PR_TITLE}> branch *${PR_BRANCH}*. Changes tested successfully. <@U01H1SLSPA8> or <@UNDRUL1EU> please, review and merge."
+#          onFailure:
+#            - >-
+#              if [[ "${PR_URL}" == null ]]; then
+#                send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. Pipeline failed on <${step_url}|${step_name}> step. PR was not created (already exists from this head branch?)"
+#              else
+#                send_notification partnersSlack --text "<${res_GitHubTFProviderXrayRepoJFrog1_gitRepoRepositoryHttpsUrl}|Terraform Provider Xray>. Pipeline failed on <${step_url}|${step_name}> step"
+#              fi
+#          onComplete:
+#            - echo "Cleaning up"
